/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as dashboardRouteImport } from './routes/(dashboard)/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as dashboardIndexImport } from './routes/(dashboard)/index'
import { Route as dashboardSearchImport } from './routes/(dashboard)/search'
import { Route as dashboardFollowImport } from './routes/(dashboard)/follow'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as dashboardProfileIndexImport } from './routes/(dashboard)/profile/index'
import { Route as dashboardProfileUsernameImport } from './routes/(dashboard)/profile/$username'
import { Route as dashboardPostPostIdImport } from './routes/(dashboard)/post/$postId'
import { Route as authResetPasswordTokenIdImport } from './routes/(auth)/reset-password/$tokenId'

// Create/Update Routes

const dashboardRouteRoute = dashboardRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const dashboardIndexRoute = dashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)

const dashboardSearchRoute = dashboardSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => dashboardRouteRoute,
} as any)

const dashboardFollowRoute = dashboardFollowImport.update({
  id: '/follow',
  path: '/follow',
  getParentRoute: () => dashboardRouteRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)

const dashboardProfileIndexRoute = dashboardProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => dashboardRouteRoute,
} as any)

const dashboardProfileUsernameRoute = dashboardProfileUsernameImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => dashboardRouteRoute,
} as any)

const dashboardPostPostIdRoute = dashboardPostPostIdImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => dashboardRouteRoute,
} as any)

const authResetPasswordTokenIdRoute = authResetPasswordTokenIdImport.update({
  id: '/reset-password/$tokenId',
  path: '/reset-password/$tokenId',
  getParentRoute: () => authRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof authRouteImport
    }
    '/(dashboard)/follow': {
      id: '/(dashboard)/follow'
      path: '/follow'
      fullPath: '/follow'
      preLoaderRoute: typeof dashboardFollowImport
      parentRoute: typeof dashboardRouteImport
    }
    '/(dashboard)/search': {
      id: '/(dashboard)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof dashboardSearchImport
      parentRoute: typeof dashboardRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexImport
      parentRoute: typeof dashboardRouteImport
    }
    '/(auth)/reset-password/$tokenId': {
      id: '/(auth)/reset-password/$tokenId'
      path: '/reset-password/$tokenId'
      fullPath: '/reset-password/$tokenId'
      preLoaderRoute: typeof authResetPasswordTokenIdImport
      parentRoute: typeof authRouteImport
    }
    '/(dashboard)/post/$postId': {
      id: '/(dashboard)/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof dashboardPostPostIdImport
      parentRoute: typeof dashboardRouteImport
    }
    '/(dashboard)/profile/$username': {
      id: '/(dashboard)/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof dashboardProfileUsernameImport
      parentRoute: typeof dashboardRouteImport
    }
    '/(dashboard)/profile/': {
      id: '/(dashboard)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof dashboardProfileIndexImport
      parentRoute: typeof dashboardRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordTokenIdRoute: typeof authResetPasswordTokenIdRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordTokenIdRoute: authResetPasswordTokenIdRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardRouteRouteChildren {
  dashboardFollowRoute: typeof dashboardFollowRoute
  dashboardSearchRoute: typeof dashboardSearchRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardPostPostIdRoute: typeof dashboardPostPostIdRoute
  dashboardProfileUsernameRoute: typeof dashboardProfileUsernameRoute
  dashboardProfileIndexRoute: typeof dashboardProfileIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardFollowRoute: dashboardFollowRoute,
  dashboardSearchRoute: dashboardSearchRoute,
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardPostPostIdRoute: dashboardPostPostIdRoute,
  dashboardProfileUsernameRoute: dashboardProfileUsernameRoute,
  dashboardProfileIndexRoute: dashboardProfileIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof dashboardIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/follow': typeof dashboardFollowRoute
  '/search': typeof dashboardSearchRoute
  '/reset-password/$tokenId': typeof authResetPasswordTokenIdRoute
  '/post/$postId': typeof dashboardPostPostIdRoute
  '/profile/$username': typeof dashboardProfileUsernameRoute
  '/profile': typeof dashboardProfileIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof dashboardIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/follow': typeof dashboardFollowRoute
  '/search': typeof dashboardSearchRoute
  '/reset-password/$tokenId': typeof authResetPasswordTokenIdRoute
  '/post/$postId': typeof dashboardPostPostIdRoute
  '/profile/$username': typeof dashboardProfileUsernameRoute
  '/profile': typeof dashboardProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(dashboard)/follow': typeof dashboardFollowRoute
  '/(dashboard)/search': typeof dashboardSearchRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(auth)/reset-password/$tokenId': typeof authResetPasswordTokenIdRoute
  '/(dashboard)/post/$postId': typeof dashboardPostPostIdRoute
  '/(dashboard)/profile/$username': typeof dashboardProfileUsernameRoute
  '/(dashboard)/profile/': typeof dashboardProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/follow'
    | '/search'
    | '/reset-password/$tokenId'
    | '/post/$postId'
    | '/profile/$username'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/follow'
    | '/search'
    | '/reset-password/$tokenId'
    | '/post/$postId'
    | '/profile/$username'
    | '/profile'
  id:
    | '__root__'
    | '/(auth)'
    | '/(dashboard)'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(dashboard)/follow'
    | '/(dashboard)/search'
    | '/(dashboard)/'
    | '/(auth)/reset-password/$tokenId'
    | '/(dashboard)/post/$postId'
    | '/(dashboard)/profile/$username'
    | '/(dashboard)/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/(dashboard)"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/forgot-password",
        "/(auth)/login",
        "/(auth)/register",
        "/(auth)/reset-password/$tokenId"
      ]
    },
    "/(dashboard)": {
      "filePath": "(dashboard)/route.tsx",
      "children": [
        "/(dashboard)/follow",
        "/(dashboard)/search",
        "/(dashboard)/",
        "/(dashboard)/post/$postId",
        "/(dashboard)/profile/$username",
        "/(dashboard)/profile/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx",
      "parent": "/(auth)"
    },
    "/(dashboard)/follow": {
      "filePath": "(dashboard)/follow.tsx",
      "parent": "/(dashboard)"
    },
    "/(dashboard)/search": {
      "filePath": "(dashboard)/search.tsx",
      "parent": "/(dashboard)"
    },
    "/(dashboard)/": {
      "filePath": "(dashboard)/index.tsx",
      "parent": "/(dashboard)"
    },
    "/(auth)/reset-password/$tokenId": {
      "filePath": "(auth)/reset-password/$tokenId.tsx",
      "parent": "/(auth)"
    },
    "/(dashboard)/post/$postId": {
      "filePath": "(dashboard)/post/$postId.tsx",
      "parent": "/(dashboard)"
    },
    "/(dashboard)/profile/$username": {
      "filePath": "(dashboard)/profile/$username.tsx",
      "parent": "/(dashboard)"
    },
    "/(dashboard)/profile/": {
      "filePath": "(dashboard)/profile/index.tsx",
      "parent": "/(dashboard)"
    }
  }
}
ROUTE_MANIFEST_END */
